name: daily-heartbeat

on:
  schedule:
    - cron: "15 7 * * *"     # 07:15 UTC daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Append heartbeat to rollup (Python)
        shell: bash
        run: |
          set -euo pipefail
          PATH_JSON="data/agi_benchmark_log.json"
          mkdir -p data
          python - <<'PY'
import json, os, datetime, sys
p = "data/agi_benchmark_log.json"
now = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
entry = {
  "run_id": "heartbeat-" + datetime.datetime.utcnow().strftime("%Y%m%d-%H%M%S"),
  "profile": "heartbeat",
  "timestamp": now,
  "tasks_total": 0,
  "tasks_passed": 0,
  "success_rate": 1.0,
}
data = []
if os.path.exists(p):
    try:
        with open(p, "r", encoding="utf-8") as f:
            obj = json.load(f)
        if isinstance(obj, list):
            data = obj
        else:
            data = [obj]
    except Exception:
        data = []
data.append(entry)
with open(p, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2)
print("Appended heartbeat:", entry)
PY

      - name: Commit & push
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add data/agi_benchmark_log.json
          git commit -m "chore(heartbeat): daily timestamp bump" || echo "Nothing to commit"
          git push
