name: Publish DS005 Report to Pages
on:
  push:
    branches: [ main ]
    paths:
      - 'reports/latest.html'
      - 'docs/**'
      - '.github/workflows/pages.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Build Pages artifact
        run: |
          set -euo pipefail
          rm -rf public && mkdir -p public
          if [ -f reports/latest.html ]; then
            cp -v reports/latest.html public/index.html
          elif [ -f docs/index.html ]; then
            cp -v docs/index.html public/index.html
          else
            printf '<!doctype html><html><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>SAVI Bench — Reports</title><style>body{font:16px/1.5 system-ui,Segoe UI,Arial,sans-serif;margin:2rem;max-width:900px}</style></head><body><h1>SAVI Bench</h1><p>No report found. See the DS005 release:</p><p><a href="https://github.com/FaithoverCP/savi-bench/releases/tag/DS005-20250908">DS005 Release</a></p></body></html>' > public/index.html
          fi
          # Include supporting docs
          [ -d docs ] && cp -rv docs/* public/ || true
      - uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - uses: actions/deploy-pages@v4

